library(phytools)
setwd("/Users/Bryan/Desktop/COVID/MORE_TANGLEGRAMS")

t1 = read.newick("original-1.nh")
t2 = read.newick("usher-1.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
right<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
pdf("original-usher-1.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


t1 = read.newick("original-2.nh")
t2 = read.newick("usher-2.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
right<-c("black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
pdf("original-usher-2.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


t1 = read.newick("original-3.nh")
t2 = read.newick("usher-3.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
right<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
pdf("original-usher-3.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


t1 = read.newick("original-4.nh")
t2 = read.newick("usher-4.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("red","black","red","black","red","black","black","black","black","black","red","black","black","black","black","red","red","red","red","black","black","black","black","black","black","black","red","black","black","black","black","black","black","black","black","red","red","black","red","black","black","black","black","black","black","black","black","black","black","red","black","black","black","black","black","red","black","black","black","black","black","black","red","black","red","black","red","black","black","black","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","black","red","black","red","red","red","red","black","black","red","black","black","black","black","black","black","black","black","black","red","black","red","black","red","red","black","black","black","black","red","black")
right<-c("red","black","red","black","red","black","black","black","black","black","red","black","black","black","black","red","red","red","red","black","black","black","black","black","black","black","red","black","black","black","black","black","black","black","black","red","red","black","red","black","black","black","black","black","black","black","black","black","black","red","black","black","black","black","black","red","black","black","black","black","black","black","red","black","red","black","red","black","black","black","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","black","red","black","red","red","red","red","black","black","red","black","black","black","black","black","black","black","black","black","red","black","red","black","red","red","black","black","black","black","red","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("red","red","black","red","black","red","black","black","black","red","red","red","black","black","black","black","red","black","black","black","black","black","black","red","red","black","red","black","black","black","black","black","black","black","black","red","black","black","black","black","black","red","black","black","black","black","red","black","red","black","red","black","black","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","red","black","red","red","red","black","black","red","black","black","black","black","black","black","black","red","black","red","red","red","black","black","black","red","black")
pdf("original-usher-4.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


t1 = read.newick("original-5.nh")
t2 = read.newick("usher-5.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("black","red","black","red","black","black","black","black","black","red","black","black","black","black","red","red","black","black","black","black","black","black","black","red","black","black","black","black","black","red","black","red","red","black","red","black","black","black","black","red","red","black","red","black","red","black","red","black","red","red","black","red","black","black","black","black","red","black","black","red","black","black","black","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","red","red","black","black","black","red","black","black","black","black","black","black","black","black","black","black","red","black","red","black","red","black","red","black","black","black","black","black","black","black","black","black")
right<-c("black","red","black","red","black","black","black","black","black","red","black","black","black","black","red","red","black","black","black","black","black","black","black","red","black","black","black","black","black","red","black","red","red","black","red","black","black","black","black","red","red","black","red","black","red","black","red","black","red","red","black","red","black","black","black","black","red","black","black","red","black","black","black","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","red","red","black","black","black","red","black","black","black","black","black","black","black","black","black","black","red","black","red","black","red","black","red","black","black","black","black","black","black","black","black","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("red","black","red","black","black","black","red","black","black","red","red","black","black","black","red","black","black","black","black","red","black","red","red","red","black","black","black","black","red","red","black","red","black","red","black","red","black","red","red","black","red","black","black","red","black","black","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","black","black","red","red","red","black","black","black","red","black","black","black","black","black","black","black","black","red","black","red","red","black","red","black","black","black","black","black","black","black")
pdf("original-usher-5.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


t1 = read.newick("original-6.nh")
t2 = read.newick("usher-6.nh")
assoc<-cbind(t1$tip.label,t2$tip.label)
obj = cophylo(t1,t2,rotate=FALSE,link.lwd=0.001)

left<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
right<-c("black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","black","black","red","red","red","black","red","red","red","red","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
edge.col<-list(left=left,right=right)
myCol = rgb(0, 0, 0, max = 255, alpha = 25)
linkCol = c("black","black","black","black","black","black","black","black","black","black","black","black","black","red","red","red","red","red","red","red","red","red","red","red","red","black","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","red","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")
pdf("original-usher-6.pdf",height=90,width=150)
plot(obj,edge.col=edge.col,pts=FALSE,tip.lty=0,tip.len=0.01,link.lwd=1,lwd=5,link.lty="solid",link.col=linkCol)
dev.off()


