find_sister_clades --generations 1 RANDOM_ADD/randomly_add_1.nh --samples MISSING_LIST/missing_10_1.list > RANDOM_ADD/randomly_add_1.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_1.nh --samples MISSING_LIST/missing_10_1.list > RANDOM_ADD/randomly_add_1.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_1.nh --samples MISSING_LIST/missing_10_1.list > RANDOM_ADD/randomly_add_1.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_2.nh --samples MISSING_LIST/missing_10_2.list > RANDOM_ADD/randomly_add_2.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_2.nh --samples MISSING_LIST/missing_10_2.list > RANDOM_ADD/randomly_add_2.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_2.nh --samples MISSING_LIST/missing_10_2.list > RANDOM_ADD/randomly_add_2.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_3.nh --samples MISSING_LIST/missing_10_3.list > RANDOM_ADD/randomly_add_3.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_3.nh --samples MISSING_LIST/missing_10_3.list > RANDOM_ADD/randomly_add_3.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_3.nh --samples MISSING_LIST/missing_10_3.list > RANDOM_ADD/randomly_add_3.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_4.nh --samples MISSING_LIST/missing_10_4.list > RANDOM_ADD/randomly_add_4.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_4.nh --samples MISSING_LIST/missing_10_4.list > RANDOM_ADD/randomly_add_4.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_4.nh --samples MISSING_LIST/missing_10_4.list > RANDOM_ADD/randomly_add_4.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_5.nh --samples MISSING_LIST/missing_10_5.list > RANDOM_ADD/randomly_add_5.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_5.nh --samples MISSING_LIST/missing_10_5.list > RANDOM_ADD/randomly_add_5.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_5.nh --samples MISSING_LIST/missing_10_5.list > RANDOM_ADD/randomly_add_5.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_6.nh --samples MISSING_LIST/missing_10_6.list > RANDOM_ADD/randomly_add_6.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_6.nh --samples MISSING_LIST/missing_10_6.list > RANDOM_ADD/randomly_add_6.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_6.nh --samples MISSING_LIST/missing_10_6.list > RANDOM_ADD/randomly_add_6.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_7.nh --samples MISSING_LIST/missing_10_7.list > RANDOM_ADD/randomly_add_7.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_7.nh --samples MISSING_LIST/missing_10_7.list > RANDOM_ADD/randomly_add_7.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_7.nh --samples MISSING_LIST/missing_10_7.list > RANDOM_ADD/randomly_add_7.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_8.nh --samples MISSING_LIST/missing_10_8.list > RANDOM_ADD/randomly_add_8.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_8.nh --samples MISSING_LIST/missing_10_8.list > RANDOM_ADD/randomly_add_8.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_8.nh --samples MISSING_LIST/missing_10_8.list > RANDOM_ADD/randomly_add_8.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_9.nh --samples MISSING_LIST/missing_10_9.list > RANDOM_ADD/randomly_add_9.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_9.nh --samples MISSING_LIST/missing_10_9.list > RANDOM_ADD/randomly_add_9.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_9.nh --samples MISSING_LIST/missing_10_9.list > RANDOM_ADD/randomly_add_9.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_10.nh --samples MISSING_LIST/missing_10_10.list > RANDOM_ADD/randomly_add_10.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_10.nh --samples MISSING_LIST/missing_10_10.list > RANDOM_ADD/randomly_add_10.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_10.nh --samples MISSING_LIST/missing_10_10.list > RANDOM_ADD/randomly_add_10.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_11.nh --samples MISSING_LIST/missing_10_11.list > RANDOM_ADD/randomly_add_11.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_11.nh --samples MISSING_LIST/missing_10_11.list > RANDOM_ADD/randomly_add_11.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_11.nh --samples MISSING_LIST/missing_10_11.list > RANDOM_ADD/randomly_add_11.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_12.nh --samples MISSING_LIST/missing_10_12.list > RANDOM_ADD/randomly_add_12.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_12.nh --samples MISSING_LIST/missing_10_12.list > RANDOM_ADD/randomly_add_12.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_12.nh --samples MISSING_LIST/missing_10_12.list > RANDOM_ADD/randomly_add_12.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_13.nh --samples MISSING_LIST/missing_10_13.list > RANDOM_ADD/randomly_add_13.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_13.nh --samples MISSING_LIST/missing_10_13.list > RANDOM_ADD/randomly_add_13.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_13.nh --samples MISSING_LIST/missing_10_13.list > RANDOM_ADD/randomly_add_13.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_14.nh --samples MISSING_LIST/missing_10_14.list > RANDOM_ADD/randomly_add_14.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_14.nh --samples MISSING_LIST/missing_10_14.list > RANDOM_ADD/randomly_add_14.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_14.nh --samples MISSING_LIST/missing_10_14.list > RANDOM_ADD/randomly_add_14.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_15.nh --samples MISSING_LIST/missing_10_15.list > RANDOM_ADD/randomly_add_15.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_15.nh --samples MISSING_LIST/missing_10_15.list > RANDOM_ADD/randomly_add_15.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_15.nh --samples MISSING_LIST/missing_10_15.list > RANDOM_ADD/randomly_add_15.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_16.nh --samples MISSING_LIST/missing_10_16.list > RANDOM_ADD/randomly_add_16.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_16.nh --samples MISSING_LIST/missing_10_16.list > RANDOM_ADD/randomly_add_16.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_16.nh --samples MISSING_LIST/missing_10_16.list > RANDOM_ADD/randomly_add_16.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_17.nh --samples MISSING_LIST/missing_10_17.list > RANDOM_ADD/randomly_add_17.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_17.nh --samples MISSING_LIST/missing_10_17.list > RANDOM_ADD/randomly_add_17.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_17.nh --samples MISSING_LIST/missing_10_17.list > RANDOM_ADD/randomly_add_17.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_18.nh --samples MISSING_LIST/missing_10_18.list > RANDOM_ADD/randomly_add_18.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_18.nh --samples MISSING_LIST/missing_10_18.list > RANDOM_ADD/randomly_add_18.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_18.nh --samples MISSING_LIST/missing_10_18.list > RANDOM_ADD/randomly_add_18.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_19.nh --samples MISSING_LIST/missing_10_19.list > RANDOM_ADD/randomly_add_19.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_19.nh --samples MISSING_LIST/missing_10_19.list > RANDOM_ADD/randomly_add_19.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_19.nh --samples MISSING_LIST/missing_10_19.list > RANDOM_ADD/randomly_add_19.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_20.nh --samples MISSING_LIST/missing_10_20.list > RANDOM_ADD/randomly_add_20.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_20.nh --samples MISSING_LIST/missing_10_20.list > RANDOM_ADD/randomly_add_20.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_20.nh --samples MISSING_LIST/missing_10_20.list > RANDOM_ADD/randomly_add_20.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_21.nh --samples MISSING_LIST/missing_10_21.list > RANDOM_ADD/randomly_add_21.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_21.nh --samples MISSING_LIST/missing_10_21.list > RANDOM_ADD/randomly_add_21.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_21.nh --samples MISSING_LIST/missing_10_21.list > RANDOM_ADD/randomly_add_21.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_22.nh --samples MISSING_LIST/missing_10_22.list > RANDOM_ADD/randomly_add_22.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_22.nh --samples MISSING_LIST/missing_10_22.list > RANDOM_ADD/randomly_add_22.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_22.nh --samples MISSING_LIST/missing_10_22.list > RANDOM_ADD/randomly_add_22.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_23.nh --samples MISSING_LIST/missing_10_23.list > RANDOM_ADD/randomly_add_23.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_23.nh --samples MISSING_LIST/missing_10_23.list > RANDOM_ADD/randomly_add_23.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_23.nh --samples MISSING_LIST/missing_10_23.list > RANDOM_ADD/randomly_add_23.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_24.nh --samples MISSING_LIST/missing_10_24.list > RANDOM_ADD/randomly_add_24.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_24.nh --samples MISSING_LIST/missing_10_24.list > RANDOM_ADD/randomly_add_24.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_24.nh --samples MISSING_LIST/missing_10_24.list > RANDOM_ADD/randomly_add_24.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_25.nh --samples MISSING_LIST/missing_10_25.list > RANDOM_ADD/randomly_add_25.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_25.nh --samples MISSING_LIST/missing_10_25.list > RANDOM_ADD/randomly_add_25.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_25.nh --samples MISSING_LIST/missing_10_25.list > RANDOM_ADD/randomly_add_25.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_26.nh --samples MISSING_LIST/missing_10_26.list > RANDOM_ADD/randomly_add_26.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_26.nh --samples MISSING_LIST/missing_10_26.list > RANDOM_ADD/randomly_add_26.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_26.nh --samples MISSING_LIST/missing_10_26.list > RANDOM_ADD/randomly_add_26.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_27.nh --samples MISSING_LIST/missing_10_27.list > RANDOM_ADD/randomly_add_27.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_27.nh --samples MISSING_LIST/missing_10_27.list > RANDOM_ADD/randomly_add_27.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_27.nh --samples MISSING_LIST/missing_10_27.list > RANDOM_ADD/randomly_add_27.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_28.nh --samples MISSING_LIST/missing_10_28.list > RANDOM_ADD/randomly_add_28.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_28.nh --samples MISSING_LIST/missing_10_28.list > RANDOM_ADD/randomly_add_28.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_28.nh --samples MISSING_LIST/missing_10_28.list > RANDOM_ADD/randomly_add_28.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_29.nh --samples MISSING_LIST/missing_10_29.list > RANDOM_ADD/randomly_add_29.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_29.nh --samples MISSING_LIST/missing_10_29.list > RANDOM_ADD/randomly_add_29.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_29.nh --samples MISSING_LIST/missing_10_29.list > RANDOM_ADD/randomly_add_29.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_30.nh --samples MISSING_LIST/missing_10_30.list > RANDOM_ADD/randomly_add_30.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_30.nh --samples MISSING_LIST/missing_10_30.list > RANDOM_ADD/randomly_add_30.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_30.nh --samples MISSING_LIST/missing_10_30.list > RANDOM_ADD/randomly_add_30.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_31.nh --samples MISSING_LIST/missing_10_31.list > RANDOM_ADD/randomly_add_31.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_31.nh --samples MISSING_LIST/missing_10_31.list > RANDOM_ADD/randomly_add_31.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_31.nh --samples MISSING_LIST/missing_10_31.list > RANDOM_ADD/randomly_add_31.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_32.nh --samples MISSING_LIST/missing_10_32.list > RANDOM_ADD/randomly_add_32.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_32.nh --samples MISSING_LIST/missing_10_32.list > RANDOM_ADD/randomly_add_32.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_32.nh --samples MISSING_LIST/missing_10_32.list > RANDOM_ADD/randomly_add_32.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_33.nh --samples MISSING_LIST/missing_10_33.list > RANDOM_ADD/randomly_add_33.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_33.nh --samples MISSING_LIST/missing_10_33.list > RANDOM_ADD/randomly_add_33.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_33.nh --samples MISSING_LIST/missing_10_33.list > RANDOM_ADD/randomly_add_33.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_34.nh --samples MISSING_LIST/missing_10_34.list > RANDOM_ADD/randomly_add_34.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_34.nh --samples MISSING_LIST/missing_10_34.list > RANDOM_ADD/randomly_add_34.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_34.nh --samples MISSING_LIST/missing_10_34.list > RANDOM_ADD/randomly_add_34.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_35.nh --samples MISSING_LIST/missing_10_35.list > RANDOM_ADD/randomly_add_35.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_35.nh --samples MISSING_LIST/missing_10_35.list > RANDOM_ADD/randomly_add_35.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_35.nh --samples MISSING_LIST/missing_10_35.list > RANDOM_ADD/randomly_add_35.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_36.nh --samples MISSING_LIST/missing_10_36.list > RANDOM_ADD/randomly_add_36.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_36.nh --samples MISSING_LIST/missing_10_36.list > RANDOM_ADD/randomly_add_36.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_36.nh --samples MISSING_LIST/missing_10_36.list > RANDOM_ADD/randomly_add_36.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_37.nh --samples MISSING_LIST/missing_10_37.list > RANDOM_ADD/randomly_add_37.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_37.nh --samples MISSING_LIST/missing_10_37.list > RANDOM_ADD/randomly_add_37.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_37.nh --samples MISSING_LIST/missing_10_37.list > RANDOM_ADD/randomly_add_37.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_38.nh --samples MISSING_LIST/missing_10_38.list > RANDOM_ADD/randomly_add_38.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_38.nh --samples MISSING_LIST/missing_10_38.list > RANDOM_ADD/randomly_add_38.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_38.nh --samples MISSING_LIST/missing_10_38.list > RANDOM_ADD/randomly_add_38.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_39.nh --samples MISSING_LIST/missing_10_39.list > RANDOM_ADD/randomly_add_39.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_39.nh --samples MISSING_LIST/missing_10_39.list > RANDOM_ADD/randomly_add_39.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_39.nh --samples MISSING_LIST/missing_10_39.list > RANDOM_ADD/randomly_add_39.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_40.nh --samples MISSING_LIST/missing_10_40.list > RANDOM_ADD/randomly_add_40.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_40.nh --samples MISSING_LIST/missing_10_40.list > RANDOM_ADD/randomly_add_40.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_40.nh --samples MISSING_LIST/missing_10_40.list > RANDOM_ADD/randomly_add_40.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_41.nh --samples MISSING_LIST/missing_10_41.list > RANDOM_ADD/randomly_add_41.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_41.nh --samples MISSING_LIST/missing_10_41.list > RANDOM_ADD/randomly_add_41.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_41.nh --samples MISSING_LIST/missing_10_41.list > RANDOM_ADD/randomly_add_41.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_42.nh --samples MISSING_LIST/missing_10_42.list > RANDOM_ADD/randomly_add_42.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_42.nh --samples MISSING_LIST/missing_10_42.list > RANDOM_ADD/randomly_add_42.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_42.nh --samples MISSING_LIST/missing_10_42.list > RANDOM_ADD/randomly_add_42.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_43.nh --samples MISSING_LIST/missing_10_43.list > RANDOM_ADD/randomly_add_43.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_43.nh --samples MISSING_LIST/missing_10_43.list > RANDOM_ADD/randomly_add_43.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_43.nh --samples MISSING_LIST/missing_10_43.list > RANDOM_ADD/randomly_add_43.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_44.nh --samples MISSING_LIST/missing_10_44.list > RANDOM_ADD/randomly_add_44.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_44.nh --samples MISSING_LIST/missing_10_44.list > RANDOM_ADD/randomly_add_44.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_44.nh --samples MISSING_LIST/missing_10_44.list > RANDOM_ADD/randomly_add_44.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_45.nh --samples MISSING_LIST/missing_10_45.list > RANDOM_ADD/randomly_add_45.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_45.nh --samples MISSING_LIST/missing_10_45.list > RANDOM_ADD/randomly_add_45.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_45.nh --samples MISSING_LIST/missing_10_45.list > RANDOM_ADD/randomly_add_45.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_46.nh --samples MISSING_LIST/missing_10_46.list > RANDOM_ADD/randomly_add_46.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_46.nh --samples MISSING_LIST/missing_10_46.list > RANDOM_ADD/randomly_add_46.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_46.nh --samples MISSING_LIST/missing_10_46.list > RANDOM_ADD/randomly_add_46.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_47.nh --samples MISSING_LIST/missing_10_47.list > RANDOM_ADD/randomly_add_47.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_47.nh --samples MISSING_LIST/missing_10_47.list > RANDOM_ADD/randomly_add_47.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_47.nh --samples MISSING_LIST/missing_10_47.list > RANDOM_ADD/randomly_add_47.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_48.nh --samples MISSING_LIST/missing_10_48.list > RANDOM_ADD/randomly_add_48.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_48.nh --samples MISSING_LIST/missing_10_48.list > RANDOM_ADD/randomly_add_48.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_48.nh --samples MISSING_LIST/missing_10_48.list > RANDOM_ADD/randomly_add_48.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_49.nh --samples MISSING_LIST/missing_10_49.list > RANDOM_ADD/randomly_add_49.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_49.nh --samples MISSING_LIST/missing_10_49.list > RANDOM_ADD/randomly_add_49.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_49.nh --samples MISSING_LIST/missing_10_49.list > RANDOM_ADD/randomly_add_49.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_50.nh --samples MISSING_LIST/missing_10_50.list > RANDOM_ADD/randomly_add_50.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_50.nh --samples MISSING_LIST/missing_10_50.list > RANDOM_ADD/randomly_add_50.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_50.nh --samples MISSING_LIST/missing_10_50.list > RANDOM_ADD/randomly_add_50.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_51.nh --samples MISSING_LIST/missing_10_51.list > RANDOM_ADD/randomly_add_51.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_51.nh --samples MISSING_LIST/missing_10_51.list > RANDOM_ADD/randomly_add_51.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_51.nh --samples MISSING_LIST/missing_10_51.list > RANDOM_ADD/randomly_add_51.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_52.nh --samples MISSING_LIST/missing_10_52.list > RANDOM_ADD/randomly_add_52.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_52.nh --samples MISSING_LIST/missing_10_52.list > RANDOM_ADD/randomly_add_52.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_52.nh --samples MISSING_LIST/missing_10_52.list > RANDOM_ADD/randomly_add_52.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_53.nh --samples MISSING_LIST/missing_10_53.list > RANDOM_ADD/randomly_add_53.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_53.nh --samples MISSING_LIST/missing_10_53.list > RANDOM_ADD/randomly_add_53.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_53.nh --samples MISSING_LIST/missing_10_53.list > RANDOM_ADD/randomly_add_53.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_54.nh --samples MISSING_LIST/missing_10_54.list > RANDOM_ADD/randomly_add_54.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_54.nh --samples MISSING_LIST/missing_10_54.list > RANDOM_ADD/randomly_add_54.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_54.nh --samples MISSING_LIST/missing_10_54.list > RANDOM_ADD/randomly_add_54.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_55.nh --samples MISSING_LIST/missing_10_55.list > RANDOM_ADD/randomly_add_55.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_55.nh --samples MISSING_LIST/missing_10_55.list > RANDOM_ADD/randomly_add_55.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_55.nh --samples MISSING_LIST/missing_10_55.list > RANDOM_ADD/randomly_add_55.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_56.nh --samples MISSING_LIST/missing_10_56.list > RANDOM_ADD/randomly_add_56.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_56.nh --samples MISSING_LIST/missing_10_56.list > RANDOM_ADD/randomly_add_56.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_56.nh --samples MISSING_LIST/missing_10_56.list > RANDOM_ADD/randomly_add_56.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_57.nh --samples MISSING_LIST/missing_10_57.list > RANDOM_ADD/randomly_add_57.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_57.nh --samples MISSING_LIST/missing_10_57.list > RANDOM_ADD/randomly_add_57.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_57.nh --samples MISSING_LIST/missing_10_57.list > RANDOM_ADD/randomly_add_57.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_58.nh --samples MISSING_LIST/missing_10_58.list > RANDOM_ADD/randomly_add_58.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_58.nh --samples MISSING_LIST/missing_10_58.list > RANDOM_ADD/randomly_add_58.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_58.nh --samples MISSING_LIST/missing_10_58.list > RANDOM_ADD/randomly_add_58.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_59.nh --samples MISSING_LIST/missing_10_59.list > RANDOM_ADD/randomly_add_59.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_59.nh --samples MISSING_LIST/missing_10_59.list > RANDOM_ADD/randomly_add_59.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_59.nh --samples MISSING_LIST/missing_10_59.list > RANDOM_ADD/randomly_add_59.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_60.nh --samples MISSING_LIST/missing_10_60.list > RANDOM_ADD/randomly_add_60.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_60.nh --samples MISSING_LIST/missing_10_60.list > RANDOM_ADD/randomly_add_60.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_60.nh --samples MISSING_LIST/missing_10_60.list > RANDOM_ADD/randomly_add_60.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_61.nh --samples MISSING_LIST/missing_10_61.list > RANDOM_ADD/randomly_add_61.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_61.nh --samples MISSING_LIST/missing_10_61.list > RANDOM_ADD/randomly_add_61.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_61.nh --samples MISSING_LIST/missing_10_61.list > RANDOM_ADD/randomly_add_61.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_62.nh --samples MISSING_LIST/missing_10_62.list > RANDOM_ADD/randomly_add_62.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_62.nh --samples MISSING_LIST/missing_10_62.list > RANDOM_ADD/randomly_add_62.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_62.nh --samples MISSING_LIST/missing_10_62.list > RANDOM_ADD/randomly_add_62.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_63.nh --samples MISSING_LIST/missing_10_63.list > RANDOM_ADD/randomly_add_63.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_63.nh --samples MISSING_LIST/missing_10_63.list > RANDOM_ADD/randomly_add_63.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_63.nh --samples MISSING_LIST/missing_10_63.list > RANDOM_ADD/randomly_add_63.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_64.nh --samples MISSING_LIST/missing_10_64.list > RANDOM_ADD/randomly_add_64.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_64.nh --samples MISSING_LIST/missing_10_64.list > RANDOM_ADD/randomly_add_64.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_64.nh --samples MISSING_LIST/missing_10_64.list > RANDOM_ADD/randomly_add_64.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_65.nh --samples MISSING_LIST/missing_10_65.list > RANDOM_ADD/randomly_add_65.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_65.nh --samples MISSING_LIST/missing_10_65.list > RANDOM_ADD/randomly_add_65.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_65.nh --samples MISSING_LIST/missing_10_65.list > RANDOM_ADD/randomly_add_65.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_66.nh --samples MISSING_LIST/missing_10_66.list > RANDOM_ADD/randomly_add_66.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_66.nh --samples MISSING_LIST/missing_10_66.list > RANDOM_ADD/randomly_add_66.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_66.nh --samples MISSING_LIST/missing_10_66.list > RANDOM_ADD/randomly_add_66.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_67.nh --samples MISSING_LIST/missing_10_67.list > RANDOM_ADD/randomly_add_67.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_67.nh --samples MISSING_LIST/missing_10_67.list > RANDOM_ADD/randomly_add_67.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_67.nh --samples MISSING_LIST/missing_10_67.list > RANDOM_ADD/randomly_add_67.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_68.nh --samples MISSING_LIST/missing_10_68.list > RANDOM_ADD/randomly_add_68.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_68.nh --samples MISSING_LIST/missing_10_68.list > RANDOM_ADD/randomly_add_68.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_68.nh --samples MISSING_LIST/missing_10_68.list > RANDOM_ADD/randomly_add_68.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_69.nh --samples MISSING_LIST/missing_10_69.list > RANDOM_ADD/randomly_add_69.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_69.nh --samples MISSING_LIST/missing_10_69.list > RANDOM_ADD/randomly_add_69.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_69.nh --samples MISSING_LIST/missing_10_69.list > RANDOM_ADD/randomly_add_69.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_70.nh --samples MISSING_LIST/missing_10_70.list > RANDOM_ADD/randomly_add_70.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_70.nh --samples MISSING_LIST/missing_10_70.list > RANDOM_ADD/randomly_add_70.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_70.nh --samples MISSING_LIST/missing_10_70.list > RANDOM_ADD/randomly_add_70.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_71.nh --samples MISSING_LIST/missing_10_71.list > RANDOM_ADD/randomly_add_71.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_71.nh --samples MISSING_LIST/missing_10_71.list > RANDOM_ADD/randomly_add_71.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_71.nh --samples MISSING_LIST/missing_10_71.list > RANDOM_ADD/randomly_add_71.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_72.nh --samples MISSING_LIST/missing_10_72.list > RANDOM_ADD/randomly_add_72.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_72.nh --samples MISSING_LIST/missing_10_72.list > RANDOM_ADD/randomly_add_72.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_72.nh --samples MISSING_LIST/missing_10_72.list > RANDOM_ADD/randomly_add_72.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_73.nh --samples MISSING_LIST/missing_10_73.list > RANDOM_ADD/randomly_add_73.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_73.nh --samples MISSING_LIST/missing_10_73.list > RANDOM_ADD/randomly_add_73.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_73.nh --samples MISSING_LIST/missing_10_73.list > RANDOM_ADD/randomly_add_73.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_74.nh --samples MISSING_LIST/missing_10_74.list > RANDOM_ADD/randomly_add_74.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_74.nh --samples MISSING_LIST/missing_10_74.list > RANDOM_ADD/randomly_add_74.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_74.nh --samples MISSING_LIST/missing_10_74.list > RANDOM_ADD/randomly_add_74.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_75.nh --samples MISSING_LIST/missing_10_75.list > RANDOM_ADD/randomly_add_75.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_75.nh --samples MISSING_LIST/missing_10_75.list > RANDOM_ADD/randomly_add_75.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_75.nh --samples MISSING_LIST/missing_10_75.list > RANDOM_ADD/randomly_add_75.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_76.nh --samples MISSING_LIST/missing_10_76.list > RANDOM_ADD/randomly_add_76.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_76.nh --samples MISSING_LIST/missing_10_76.list > RANDOM_ADD/randomly_add_76.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_76.nh --samples MISSING_LIST/missing_10_76.list > RANDOM_ADD/randomly_add_76.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_77.nh --samples MISSING_LIST/missing_10_77.list > RANDOM_ADD/randomly_add_77.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_77.nh --samples MISSING_LIST/missing_10_77.list > RANDOM_ADD/randomly_add_77.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_77.nh --samples MISSING_LIST/missing_10_77.list > RANDOM_ADD/randomly_add_77.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_78.nh --samples MISSING_LIST/missing_10_78.list > RANDOM_ADD/randomly_add_78.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_78.nh --samples MISSING_LIST/missing_10_78.list > RANDOM_ADD/randomly_add_78.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_78.nh --samples MISSING_LIST/missing_10_78.list > RANDOM_ADD/randomly_add_78.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_79.nh --samples MISSING_LIST/missing_10_79.list > RANDOM_ADD/randomly_add_79.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_79.nh --samples MISSING_LIST/missing_10_79.list > RANDOM_ADD/randomly_add_79.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_79.nh --samples MISSING_LIST/missing_10_79.list > RANDOM_ADD/randomly_add_79.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_80.nh --samples MISSING_LIST/missing_10_80.list > RANDOM_ADD/randomly_add_80.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_80.nh --samples MISSING_LIST/missing_10_80.list > RANDOM_ADD/randomly_add_80.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_80.nh --samples MISSING_LIST/missing_10_80.list > RANDOM_ADD/randomly_add_80.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_81.nh --samples MISSING_LIST/missing_10_81.list > RANDOM_ADD/randomly_add_81.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_81.nh --samples MISSING_LIST/missing_10_81.list > RANDOM_ADD/randomly_add_81.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_81.nh --samples MISSING_LIST/missing_10_81.list > RANDOM_ADD/randomly_add_81.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_82.nh --samples MISSING_LIST/missing_10_82.list > RANDOM_ADD/randomly_add_82.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_82.nh --samples MISSING_LIST/missing_10_82.list > RANDOM_ADD/randomly_add_82.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_82.nh --samples MISSING_LIST/missing_10_82.list > RANDOM_ADD/randomly_add_82.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_83.nh --samples MISSING_LIST/missing_10_83.list > RANDOM_ADD/randomly_add_83.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_83.nh --samples MISSING_LIST/missing_10_83.list > RANDOM_ADD/randomly_add_83.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_83.nh --samples MISSING_LIST/missing_10_83.list > RANDOM_ADD/randomly_add_83.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_84.nh --samples MISSING_LIST/missing_10_84.list > RANDOM_ADD/randomly_add_84.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_84.nh --samples MISSING_LIST/missing_10_84.list > RANDOM_ADD/randomly_add_84.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_84.nh --samples MISSING_LIST/missing_10_84.list > RANDOM_ADD/randomly_add_84.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_85.nh --samples MISSING_LIST/missing_10_85.list > RANDOM_ADD/randomly_add_85.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_85.nh --samples MISSING_LIST/missing_10_85.list > RANDOM_ADD/randomly_add_85.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_85.nh --samples MISSING_LIST/missing_10_85.list > RANDOM_ADD/randomly_add_85.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_86.nh --samples MISSING_LIST/missing_10_86.list > RANDOM_ADD/randomly_add_86.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_86.nh --samples MISSING_LIST/missing_10_86.list > RANDOM_ADD/randomly_add_86.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_86.nh --samples MISSING_LIST/missing_10_86.list > RANDOM_ADD/randomly_add_86.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_87.nh --samples MISSING_LIST/missing_10_87.list > RANDOM_ADD/randomly_add_87.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_87.nh --samples MISSING_LIST/missing_10_87.list > RANDOM_ADD/randomly_add_87.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_87.nh --samples MISSING_LIST/missing_10_87.list > RANDOM_ADD/randomly_add_87.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_88.nh --samples MISSING_LIST/missing_10_88.list > RANDOM_ADD/randomly_add_88.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_88.nh --samples MISSING_LIST/missing_10_88.list > RANDOM_ADD/randomly_add_88.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_88.nh --samples MISSING_LIST/missing_10_88.list > RANDOM_ADD/randomly_add_88.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_89.nh --samples MISSING_LIST/missing_10_89.list > RANDOM_ADD/randomly_add_89.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_89.nh --samples MISSING_LIST/missing_10_89.list > RANDOM_ADD/randomly_add_89.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_89.nh --samples MISSING_LIST/missing_10_89.list > RANDOM_ADD/randomly_add_89.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_90.nh --samples MISSING_LIST/missing_10_90.list > RANDOM_ADD/randomly_add_90.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_90.nh --samples MISSING_LIST/missing_10_90.list > RANDOM_ADD/randomly_add_90.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_90.nh --samples MISSING_LIST/missing_10_90.list > RANDOM_ADD/randomly_add_90.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_91.nh --samples MISSING_LIST/missing_10_91.list > RANDOM_ADD/randomly_add_91.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_91.nh --samples MISSING_LIST/missing_10_91.list > RANDOM_ADD/randomly_add_91.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_91.nh --samples MISSING_LIST/missing_10_91.list > RANDOM_ADD/randomly_add_91.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_92.nh --samples MISSING_LIST/missing_10_92.list > RANDOM_ADD/randomly_add_92.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_92.nh --samples MISSING_LIST/missing_10_92.list > RANDOM_ADD/randomly_add_92.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_92.nh --samples MISSING_LIST/missing_10_92.list > RANDOM_ADD/randomly_add_92.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_93.nh --samples MISSING_LIST/missing_10_93.list > RANDOM_ADD/randomly_add_93.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_93.nh --samples MISSING_LIST/missing_10_93.list > RANDOM_ADD/randomly_add_93.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_93.nh --samples MISSING_LIST/missing_10_93.list > RANDOM_ADD/randomly_add_93.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_94.nh --samples MISSING_LIST/missing_10_94.list > RANDOM_ADD/randomly_add_94.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_94.nh --samples MISSING_LIST/missing_10_94.list > RANDOM_ADD/randomly_add_94.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_94.nh --samples MISSING_LIST/missing_10_94.list > RANDOM_ADD/randomly_add_94.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_95.nh --samples MISSING_LIST/missing_10_95.list > RANDOM_ADD/randomly_add_95.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_95.nh --samples MISSING_LIST/missing_10_95.list > RANDOM_ADD/randomly_add_95.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_95.nh --samples MISSING_LIST/missing_10_95.list > RANDOM_ADD/randomly_add_95.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_96.nh --samples MISSING_LIST/missing_10_96.list > RANDOM_ADD/randomly_add_96.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_96.nh --samples MISSING_LIST/missing_10_96.list > RANDOM_ADD/randomly_add_96.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_96.nh --samples MISSING_LIST/missing_10_96.list > RANDOM_ADD/randomly_add_96.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_97.nh --samples MISSING_LIST/missing_10_97.list > RANDOM_ADD/randomly_add_97.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_97.nh --samples MISSING_LIST/missing_10_97.list > RANDOM_ADD/randomly_add_97.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_97.nh --samples MISSING_LIST/missing_10_97.list > RANDOM_ADD/randomly_add_97.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_98.nh --samples MISSING_LIST/missing_10_98.list > RANDOM_ADD/randomly_add_98.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_98.nh --samples MISSING_LIST/missing_10_98.list > RANDOM_ADD/randomly_add_98.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_98.nh --samples MISSING_LIST/missing_10_98.list > RANDOM_ADD/randomly_add_98.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_99.nh --samples MISSING_LIST/missing_10_99.list > RANDOM_ADD/randomly_add_99.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_99.nh --samples MISSING_LIST/missing_10_99.list > RANDOM_ADD/randomly_add_99.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_99.nh --samples MISSING_LIST/missing_10_99.list > RANDOM_ADD/randomly_add_99.n3.sister_clades
find_sister_clades --generations 1 RANDOM_ADD/randomly_add_100.nh --samples MISSING_LIST/missing_10_100.list > RANDOM_ADD/randomly_add_100.n1.sister_clades
find_sister_clades --generations 2 RANDOM_ADD/randomly_add_100.nh --samples MISSING_LIST/missing_10_100.list > RANDOM_ADD/randomly_add_100.n2.sister_clades
find_sister_clades --generations 3 RANDOM_ADD/randomly_add_100.nh --samples MISSING_LIST/missing_10_100.list > RANDOM_ADD/randomly_add_100.n3.sister_clades